=== cityindex-attic/CIAPI.Java/src/CodeGeneration/files/code_replacement_rules/replacement_rule.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.w3schools.com" xmlns="http://www.w3schools.com"
	elementFormDefault="qualified">
	<xs:element name="replacementRoot">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="replacement" type="replacement"
					minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="replacementSet" type="replacementSet"
					minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="objName" type="xs:string" />
			<xs:attribute name="extraArgs" type="xs:string" />
		</xs:complexType>
	</xs:element>
	<xs:complexType name="replacements">
		<xs:sequence>
			<xs:element name="replacement" type="replacement"
				minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="replacementSet" type="replacementSet"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="replacement">
		<xs:all>
			<xs:element name="templateValue" minOccurs="1" maxOccurs="1" />
			<xs:element name="objectValue" minOccurs="1" maxOccurs="1" />
		</xs:all>
	</xs:complexType>
	<xs:complexType name="replacementSet">
		<xs:all>
			<xs:element name="templateValue" minOccurs="1" maxOccurs="1" />
			<xs:element name="objectValue" minOccurs="1" maxOccurs="1" />
			<xs:element name="replacements" type="replacements" />
		</xs:all>
		<xs:attribute name="subObjName" type="xs:string" />
	</xs:complexType>
</xs:schema>

=== cityindex-attic/CIAPI.Java/src/CodeGeneration/files/code_replacement_rules/schema_replacement_rule.xml
<?xml version="1.0" encoding="UTF-8"?>
<replacementRoot xmlns="http://www.w3schools.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="replacement_rule.xsd"
	objName="smd" extraArgs="args" templateLocation="../code_templates/CombinedTemplate.jav"
	objectType="codegen.modelobjects.SMDDescriptor">
	<fileName value="@ServiceMethods.java" />
	<replacement name="packageName" value="$args[0]" />
	<replacementSet subObjName="method" name="methods"
		value="smd.getServices().entrySet()">
		<replacement name="description" value="method.getValue().getDescription()" />
		<replacement name="return"
			value="method.getValue().getReturns().get$ref($args[1])" />
		<replacement name="name" value="method.getKey()" />
		<replacementSet subObjName="p" name="parameters"
			value="method.getValue().getParameters()">
			<replacement name="pType" value="p.getType($args[1])" />
			<replacement name="pName" value="p.getName()" />
		</replacementSet>
	</replacementSet>
</replacementRoot>

=== cityindex-attic/CIAPI.Java/src/CodeGeneration/files/code_replacement_rules/schema_replacement_impl_rule.xml
<?xml version="1.0" encoding="UTF-8"?>
<replacementRoot xmlns="http://www.w3schools.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="files/code_replacement_rules/replacement_rule.xsd"
	objName="smd" extraArgs="args">
	<replacement>
		<templateValue>packageName</templateValue>
		<objectValue>$args[0]</objectValue>
	</replacement>
	<replacementSet subObjName="method">
		<templateValue>methods</templateValue>
		<objectValue>smd.getServices().entrySet()</objectValue>
		<replacements>
			<replacement>
				<templateValue>description</templateValue>
				<objectValue>method.getValue().getDescription()</objectValue>
			</replacement>
			<replacement>
				<templateValue>return</templateValue>
				<objectValue>method.getValue().getReturn()</objectValue>
			</replacement>
			<replacement>
				<templateValue>name</templateValue>
				<objectValue>method.getKey()</objectValue>
			</replacement>
			
		</replacements>
	</replacementSet>
</replacementRoot>

=== cityindex-attic/CIAPI.Java/src/CodeGeneration/files/code_replacement_rules/dto_replacement_rule.xml
<?xml version="1.0" encoding="UTF-8"?>
<replacementRoot xmlns="http://www.w3schools.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="replacement_rule.xsd"
	objName="dto" templateLocation="../code_templates/DTOTemplate.jav"
	objectType="codegen.modelobjects.DTO">
	<fileName value="@dto/dto.getName()+@.java" />
	<replacement name="name" value="dto.getName()" />
	<replacement name="description" value="dto.getDescription()" />
	<replacementSet subObjName="prop" name="properties"
		value="dto.getProperties().entrySet()">
		<replacement name="propDesc" value="prop.getValue().getDescription()" />
		<replacement name="propertyName" value="prop.getKey()" />
		<replacement name="propertyType" value="prop.getValue().getType()" />
	</replacementSet>
</replacementRoot>
